/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#000000",
        "primary": "#9cff93",
        "outline-variant": "#494847",
        "on-background": "#ffffff",
        "tertiary-dim": "#edeaea",
        "secondary-dim": "#00d4ec",
        "surface-dim": "#0e0e0e",
        "surface-tint": "#9cff93",
        "surface": "#0e0e0e",
        "tertiary-fixed-dim": "#f3f0ef",
        "on-tertiary": "#605f5e",
        "on-tertiary-fixed-variant": "#6e6d6d",
        "on-primary": "#006413",
        "on-primary-container": "#005a10",
        "on-error-container": "#ffd2c8",
        "secondary-container": "#006875",
        "on-secondary-container": "#e8fbff",
        "inverse-surface": "#fcf8f8",
        "primary-dim": "#00ec3b",
        "on-surface": "#ffffff",
        "primary-container": "#00fc40",
        "inverse-on-surface": "#565554",
        "primary-fixed": "#00fc40",
        "on-tertiary-fixed": "#515050",
        "on-primary-fixed-variant": "#006513",
        "outline": "#777575",
        "on-primary-fixed": "#00440a",
        "surface-bright": "#2c2c2c",
        "on-surface-variant": "#adaaaa",
        "tertiary-fixed": "#ffffff",
        "surface-container-highest": "#262626",
        "surface-container-low": "#131313",
        "error-dim": "#d53d18",
        "surface-container": "#1a1919",
        "on-tertiary-container": "#575656",
        "primary-fixed-dim": "#00ec3b",
        "surface-container-high": "#201f1f",
        "secondary-fixed-dim": "#00d7f0",
        "surface-variant": "#262626",
        "inverse-primary": "#006f16",
        "on-secondary-fixed": "#003a42",
        "on-error": "#450900",
        "error": "#ff7351",
        "secondary": "#00e3fd",
        "on-secondary": "#004d57",
        "background": "#0e0e0e",
        "secondary-fixed": "#26e6ff",
        "on-secondary-fixed-variant": "#005964",
        "tertiary-container": "#edeaea",
        "tertiary": "#fcf9f8",
        "error-container": "#b92902",
        "surface-container-lowest": "#050505",
        "surface-lowest": "#050505",
        "surface-low": "#0e0e0e",
        "surface-medium": "#131313",
        "surface-high": "#1a1919",
        "surface-highest": "#262626",
        "glass-blur": "rgba(29, 29, 29, 0.6)",
      },
      backgroundImage: {
        "primary-gradient": "linear-gradient(135deg, #9cff93 0%, #00fc40 100%)",
        "secondary-gradient": "linear-gradient(135deg, #00e3fd 0%, #00d7f0 100%)",
        "surface-gradient": "linear-gradient(180deg, transparent 0%, rgba(5, 5, 5, 0.8) 100%)",
      },
      boxShadow: {
        "primary-glow": "0 0 20px rgba(156, 255, 147, 0.3)",
        "secondary-glow": "0 0 20px rgba(0, 227, 253, 0.3)",
        "luxury-float": "0 20px 50px rgba(0, 0, 0, 0.5)",
      },
      fontFamily: {
        "inter": ["Inter", "sans-serif"],
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      letterSpacing: {
        "compressed": "-0.04em",
        "tightest": "-0.02em",
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
